---
default_install_hook_types: ["pre-commit", "pre-push"]
default_stages: ["commit"]
exclude: ^\.gitleaks\.toml$
minimum_pre_commit_version: 2.18.0
repos:
  # Security
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        stages: ["commit", "push"]
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
        stages: ["commit", "push"]
  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint-fix
  # Shell
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.2
    hooks:
      - id: shellcheck
        stages: ["push"]
  # Yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
  # Other
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
      - id: check-json
      - id: detect-private-key
        stages: ["commit", "push"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
      - id: trailing-whitespace
ci:
  autofix_prs: false
