---
name: Setup COBOL

on: push

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run fabasoad/setup-cobol-action@master
        uses: ./
      - name: Run script
        run: |
          cobc -x HelloWorld.cob
          ./HelloWorld
